### ISSUE TITLE
Data request for species Rex Sole

### ISSUE THREAD

**Issue by emilysellinger** [pfmc-assessments/PacFIN.Utilities#105] opened 2023-03-31 19:00 UTC
### Identify the common name(s) or PacFIN species code(s)

REX

### Type of data needed

biological data

### Additional information

Curious if the issue with duplicated records in California for 2021 and 2022 has been resolved

### Do you you have clearance to access these data?

- [X] I agree that I have clearance (as described above)

**Comment by chantelwetzel-noaa** [comment] 2023-03-31 23:49
@okenk @gertsevv I have uploaded the bds data for rex sole to the network.  

@kellijohnson-NOAA The bds pull function is still flagging duplicate records, however, they are now being removed correctly and the function is able to fully run.  To me this appears that the issue is still present but fixed to the extent that we can now thread the multiple age reads into the bds data correctly.  Let me know if you have concerns about this and we can look at this again next week to confirm if needed.

**Comment by kellijohnson-NOAA** [comment] 2023-04-05 14:01
Thanks @chantelwetzel-noaa I double checked that the records are in fact exact duplicates and that we are not missing out on any information. The important thing to look for when downloading the records and the warning comes up is that all the noted records are from California and in 2021 and/or 2022. If they aren't then there may be problems. I am going to add an additional if statement that will look for this. Thanks for reminding me that I needed to work on it 😄. I will close this issue once that check is in place.

**Comment by chantelwetzel-noaa** [comment] 2023-04-05 14:13
Perfect. This additional information is very helpful.

**Closed** 2023-04-06 06:54 UTC
Labels: type: request
